/**
 * ActionTypes for fetching weather by current location
 *
 */
export const REQUEST_CURRENT_LOCATION_WEATHER = 'REQUEST_CURRENT_LOCATION_WEATHER';
export const SUCCESS_CURRENT_LOCATION_WEATHER = 'SUCCESS_CURRENT_LOCATION_WEATHER';
export const ERROR_CURRENT_LOCATION_WEATHER   = 'ERROR_CURRENT_LOCATION_WEATHER';
